[1m============================= test session starts ==============================[0m
platform linux -- Python 3.10.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
cachedir: /workspaces/codespace/ros2/project/tutorial/build/examples_rclpy_pointcloud_publisher/.pytest_cache
rootdir: /workspaces/codespace/ros2/project/tutorial/src/examples/rclpy, configfile: pytest.ini
plugins: colcon-core-0.15.2
[1mcollecting ... [0m[1m
collected 0 items / 3 errors                                                   [0m

==================================== ERRORS ====================================
[31m[1m_____ ERROR collecting topics/pointcloud_publisher/test/test_copyright.py ______[0m
[31mImportError while importing test module '/workspaces/codespace/ros2/project/tutorial/src/examples/rclpy/topics/pointcloud_publisher/test/test_copyright.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test/test_copyright.py:15: in <module>
    from ament_copyright.main import main
E   ModuleNotFoundError: No module named 'ament_copyright'[0m
[31m[1m_______ ERROR collecting topics/pointcloud_publisher/test/test_flake8.py _______[0m
[31mImportError while importing test module '/workspaces/codespace/ros2/project/tutorial/src/examples/rclpy/topics/pointcloud_publisher/test/test_flake8.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/test_flake8.py:18: in <module>
    from ament_flake8.main import main
E   ModuleNotFoundError: No module named 'ament_flake8'

During handling of the above exception, another exception occurred:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test/test_flake8.py:20: in <module>
    from ament_flake8.main import main_with_errors
E   ModuleNotFoundError: No module named 'ament_flake8'[0m
[31m[1m_______ ERROR collecting topics/pointcloud_publisher/test/test_pep257.py _______[0m
[31mImportError while importing test module '/workspaces/codespace/ros2/project/tutorial/src/examples/rclpy/topics/pointcloud_publisher/test/test_pep257.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test/test_pep257.py:15: in <module>
    from ament_pep257.main import main
E   ModuleNotFoundError: No module named 'ament_pep257'[0m
- generated xml file: /workspaces/codespace/ros2/project/tutorial/build/examples_rclpy_pointcloud_publisher/pytest.xml -
=========================== short test summary info ============================
ERROR test/test_copyright.py
ERROR test/test_flake8.py
ERROR test/test_pep257.py
!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!
[31m============================== [31m[1m3 errors[0m[31m in 0.06s[0m[31m ===============================[0m
